### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by chiptus** [ant4g0nist/chinstrap#2]
Is there a chance to have a docker image so we can install it with a oneliner and without deps?

**Comment by ant4g0nist** [comment]
yes, it should be possible. Sandbox would be a concern as I am using docker to launch Flextesa container from inside chinstrap. Would be Dockerception!

![dockerception](https://user-images.githubusercontent.com/3500559/127734073-1fffb5cd-5ba9-48ba-9267-25de992a3006.jpg)

**Comment by chiptus** [comment]
If you expose the docker socket, and add the docker binary to the image (or
use its api) , it's possible

**Comment by ant4g0nist** [comment]
done!

```bash
docker run -v /var/run/docker.sock:/var/run/docker.sock -it ant4g0nist/chinstrap:0.0.13
```

**Comment by chiptus** [comment]
Awesome, thanks! That was really fast!

**Comment by ant4g0nist** [comment]
Is that good for now? :)

**Comment by chiptus** [comment]
I guess the image is built for mac, right?

```
he requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

can we have an amd64 image?

**Comment by chiptus** [comment]
building it locally worked, I think.

why the entrypoing of the image is bash and not `chinstrap`?

I expect to see the regular output of chinstrap when I'm running the image.

When I run `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -it chinstrap:local chinstrap` I get:

```
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
/usr/local/bin/chinstrap: line 3: from: command not found
/usr/local/bin/chinstrap: chinstrap: line 6: syntax error near unexpected token `('
/usr/local/bin/chinstrap: chinstrap: line 6: `    with warnings.catch_warnings():'
```

**Comment by ant4g0nist** [comment]
Okay. thanks for checking it. fixed and pushed both arm and amd images and made chinstrap the entrypoint.

note: the target folder needs to be shared with Docker

```bash
docker run -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/home -it ant4g0nist/chinstrap:0.0.13 --init
```

<img width="957" alt="Screenshot 2021-08-01 at 17 02 05" src="https://user-images.githubusercontent.com/3500559/127775643-95872b5c-75f0-4726-b692-bfe73c6c6f5c.png">
