### ISSUE TITLE
"--originate" perform tests

### ISSUE THREAD

**Issue by fleandrei** [ant4g0nist/chinstrap#3]
Hi, I use chinstrap with docker as expressed in README via the following command: 
_docker run -v `pwd`:/home --rm -it ant4g0nist/chinstrap_

when I run the _--originate_ option, chinstrap actually performs _--test pytest_ command instead of originating contracts.
I have the same issue with other commands such as _--debug_  or _--network_ .

**Comment by ant4g0nist** [comment]
Hey @fleandrei, sorry for the delay. I have been traveling last few weeks. The issue should be fixed now. it was a really stupid mistake. my bad. Please let me know if you face any further issues. thanks

**Comment by fleandrei** [comment]
Hi, thanks the issue I raised is fixed. 
However I have another one now : when I run the --originate option, I get "Exception occured while loading accounts! [Errno 2] No such file or directory: '/root/.tezos-client/secret_keys'"

The ./.priv.tz file is not considered.

**Comment by ant4g0nist** [comment]
have you configured accounts in chinstrap_config.yaml ?
